In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import spglib
from pymatgen.io.ase import AseAtomsAdaptor
from monty.serialization import loadfn

In [2]:
entries = loadfn("../data/MP_data-50.json.gz")

In [3]:
for id in entries.keys():
    MP_structure = AseAtomsAdaptor.get_atoms(entries[id]["structure"])
    lattice = MP_structure.get_cell()
    positions = MP_structure.get_scaled_positions()
    numbers = MP_structure.get_atomic_numbers()
    cell = (lattice, positions, numbers)
    
    spacegroup = spglib.get_spacegroup(cell, symprec=1e-05, symbol_type=0)
    name, number = spacegroup.split(' ')
    symm = spglib.get_symmetry_dataset(cell)

    print(id,name,number[1:-1])
    print(symm["hall_number"])

mp-1 Im-3m 229
529
mp-10 Pm-3m 221
517
mp-11 R-3m 166
458
mp-2 Fm-3m 225
523
mp-3 I4_1/amd 141
426
mp-4 Im-3m 229
529
mp-7 R-3 148
436
mp-8 P6_3/mmc 194
488
mp-9 Fm-3m 225
523
mp-24 Ia-3 206
502
mp-25 Pa-3 205
501
mp-26 P6_3/mmc 194
488
mp-27 Fm-3m 225
523
mp-28 Fm-3m 225
523
mp-30 Fm-3m 225
523
mp-32 Fd-3m 227
525
mp-33 P6_3/mmc 194
488
mp-34 P6/mmm 191
485
mp-35 I-43m 217
513
mp-13 C2/m 12
63
mp-14 P1 1
1
mp-17 Pm-3n 223
520
mp-18 P6_3/mmc 194
488
mp-19 C2 5
9
mp-20 Im-3m 229
529
mp-21 Fmmm 69
334
mp-23 Fm-3m 225
523
mp-36 I4/mmm 139
424
mp-37 I4/mmm 139
424
mp-38 P6_3/mmc 194
488
mp-39 Im-3m 229
529
mp-41 Im-3m 229
529
mp-42 P-42_1m 113
390
mp-43 Cm 8
30
mp-44 Cmcm 63
298
mp-45 Fm-3m 225
523
mp-46 P6_3/mmc 194
488
mp-47 P6_3/mmc 194
488
mp-48 P6_3/mmc 194
488
mp-49 P6_3/mmc 194
488

In [55]:
data = pd.read_csv("spglib_wyckoff.csv")
Info = data.loc[data['Hall number'] == symm["hall_number"]].reset_index(drop=True)["Info"][0]
print("Info:",Info[1:])
newdata = data.loc[data['Hall number'] == symm["hall_number"]].reset_index(drop=True)
newdata.head()

Info: P 6sub3/m 2/m 2/c

,Multiplicity,Wyckoff letter,Sitesymmetry,Coordinates,Hall number,Info
0,24,l,1,"(x,y,z) (-y,x-y,z) (-x+y,-x,z) (-x,-y,z+1/2) (...",488,P 6sub3/m 2/m 2/c
1,12,k,.m.,"(x,2x,z) (-2x,-x,z) (x,-x,z) (-x,-2x,z+1/2) (2...",488,P 6sub3/m 2/m 2/c
2,12,j,m..,"(x,y,1/4) (-y,x-y,1/4) (-x+y,-x,1/4) (-x,-y,3/...",488,P 6sub3/m 2/m 2/c
3,12,i,.2.,"(x,0,0) (0,x,0) (-x,-x,0) (-x,0,1/2) (0,-x,1/2...",488,P 6sub3/m 2/m 2/c
4,6,h,mm2,"(x,2x,1/4) (-2x,-x,1/4) (x,-x,1/4) (-x,-2x,3/4...",488,P 6sub3/m 2/m 2/c

In [57]:
newdata = data.loc[data['Info'] == " P 6sub3/m 2/m 2/c"].reset_index(drop=True)
hall_num = data.loc[data['Info'] == " P 6sub3/m 2/m 2/c"].reset_index(drop=True)["Hall number"][0]
print("hall num", hall_num)
newdata.head()

hall num 488

,Multiplicity,Wyckoff letter,Sitesymmetry,Coordinates,Hall number,Info
0,24,l,1,"(x,y,z) (-y,x-y,z) (-x+y,-x,z) (-x,-y,z+1/2) (...",488,P 6sub3/m 2/m 2/c
1,12,k,.m.,"(x,2x,z) (-2x,-x,z) (x,-x,z) (-x,-2x,z+1/2) (2...",488,P 6sub3/m 2/m 2/c
2,12,j,m..,"(x,y,1/4) (-y,x-y,1/4) (-x+y,-x,1/4) (-x,-y,3/...",488,P 6sub3/m 2/m 2/c
3,12,i,.2.,"(x,0,0) (0,x,0) (-x,-x,0) (-x,0,1/2) (0,-x,1/2...",488,P 6sub3/m 2/m 2/c
4,6,h,mm2,"(x,2x,1/4) (-2x,-x,1/4) (x,-x,1/4) (-x,-2x,3/4...",488,P 6sub3/m 2/m 2/c